"""add reflect tables

Revision ID: 28cf671fef75
Revises: 72e7e69c3e21
Create Date: 2026-07-04 13:27:27.741353+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28cf671fef75"
down_revision: str | None = "72e7e69c3e21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reflect_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="reflect_sessions_user_id_key"),
    )
    op.create_index(
        "idx_reflect_sessions_user", "reflect_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "reflect_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')", name="reflect_messages_role_check"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["reflect_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reflect_messages_session_date",
        "reflect_messages",
        ["session_id", "date", "created_at"],
        unique=False,
    )
    op.execute(
        "CREATE INDEX idx_reflect_messages_session_created ON reflect_messages(session_id, created_at DESC)"
    )
    op.create_table(
        "reflect_entries",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_message_id"], ["reflect_messages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["reflect_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "date", name="reflect_entries_session_date_key"
        ),
    )
    op.create_index(
        "idx_reflect_entries_session_date",
        "reflect_entries",
        ["session_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reflect_entries_session_date", table_name="reflect_entries")
    op.drop_table("reflect_entries")
    op.drop_index("idx_reflect_messages_session_date", table_name="reflect_messages")
    op.execute("DROP INDEX IF EXISTS idx_reflect_messages_session_created")
    op.drop_table("reflect_messages")
    op.drop_index("idx_reflect_sessions_user", table_name="reflect_sessions")
    op.drop_table("reflect_sessions")
    # ### end Alembic commands ###
