"""add_content_hash_to_entries_and_summaries

Revision ID: bcbce1c99889
Revises: ed989bc239da
Create Date: 2026-07-04 04:35:40.848545+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcbce1c99889"
down_revision: str | None = "ed989bc239da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_entries", sa.Column("content_hash", sa.Text(), nullable=True)
    )
    op.add_column("summaries", sa.Column("content_hash", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summaries", "content_hash")
    op.drop_column("journal_entries", "content_hash")
    # ### end Alembic commands ###
