"""add_media_upload_status_and_split_processing_state

Revision ID: 52903c9f9328
Revises: 7c8cae8aead6
Create Date: 2026-07-02 17:32:17.247890+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52903c9f9328'
down_revision: str | None = '7c8cae8aead6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new enum type before adding the column.
    op.execute("CREATE TYPE media_upload_status AS ENUM ('pending', 'uploaded', 'expired')")
    op.add_column('media', sa.Column('upload_status', sa.Enum('pending', 'uploaded', 'expired', name='media_upload_status'), nullable=False))
    op.add_column('media', sa.Column('upload_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('media', 'processing_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='media_processing_status'),
               nullable=True)
    op.drop_index(op.f('idx_media_pending'), table_name='media', postgresql_where="(processing_status = ANY (ARRAY['pending'::media_processing_status, 'processing'::media_processing_status]))")
    op.create_index('idx_media_pending_processing', 'media', ['processing_status'], unique=False, postgresql_where=sa.text("processing_status IN ('pending', 'processing')"))
    op.create_index('idx_media_stale_upload', 'media', ['upload_expires_at'], unique=False, postgresql_where=sa.text("upload_status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_media_stale_upload', table_name='media', postgresql_where=sa.text("upload_status = 'pending'"))
    op.drop_index('idx_media_pending_processing', table_name='media', postgresql_where=sa.text("processing_status IN ('pending', 'processing')"))
    op.create_index(op.f('idx_media_pending'), 'media', ['processing_status'], unique=False, postgresql_where="(processing_status = ANY (ARRAY['pending'::media_processing_status, 'processing'::media_processing_status]))")
    op.alter_column('media', 'processing_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='media_processing_status'),
               nullable=False)
    op.drop_column('media', 'upload_expires_at')
    op.drop_column('media', 'upload_status')
    op.execute("DROP TYPE media_upload_status")
    # ### end Alembic commands ###
