"""add recall tables

Revision ID: 72e7e69c3e21
Revises: bcbce1c99889
Create Date: 2026-07-04 07:59:39.849562+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "72e7e69c3e21"
down_revision: str | None = "bcbce1c99889"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recall_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="recall_sessions_user_id_key"),
    )
    op.create_index(
        "idx_recall_sessions_user", "recall_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "recall_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "retrieved_entries", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')", name="recall_messages_role_check"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["recall_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_recall_messages_session",
        "recall_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    # Create custom functional index for date-based lookups
    op.execute(
        "CREATE INDEX idx_recall_messages_date ON recall_messages(session_id, ((created_at AT TIME ZONE 'UTC')::date), created_at ASC)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_recall_messages_date")
    op.drop_index("idx_recall_messages_session", table_name="recall_messages")
    op.drop_table("recall_messages")
    op.drop_index("idx_recall_sessions_user", table_name="recall_sessions")
    op.drop_table("recall_sessions")
    # ### end Alembic commands ###
