"""init_schema

Revision ID: 66a2a2a2e1b4
Revises:
Create Date: 2026-07-02 06:34:52.486117+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66a2a2a2e1b4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Enable extensions required by the DayCache schema
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moods",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("avatar_key", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "collections",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name = lower(name)", name="collections_name_lower_check"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="collections_user_id_name_key"),
    )
    op.create_index("idx_collections_user_id", "collections", ["user_id"], unique=False)
    op.create_table(
        "days",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weather", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="days_user_id_date_key"),
    )
    op.create_index(
        "idx_days_user_date",
        "days",
        ["user_id", sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_table(
        "devices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_identifier", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum("web", "ios", "android", name="device_platform"),
            nullable=False,
        ),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "device_identifier", name="devices_user_id_device_identifier_key"
        ),
    )
    op.create_index("idx_devices_user_id", "devices", ["user_id"], unique=False)
    op.create_table(
        "media",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column(
            "media_type", sa.Enum("image", "video", name="media_type"), nullable=False
        ),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("color_palette", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("blurhash", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                name="media_processing_status",
            ),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::JSONB"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        "idx_media_pending",
        "media",
        ["processing_status"],
        unique=False,
        postgresql_where=sa.text("processing_status IN ('pending', 'processing')"),
    )
    op.create_index("idx_media_user_id", "media", ["user_id"], unique=False)
    op.create_table(
        "oauth_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("google", "apple", "github", name="oauth_provider"),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.Text(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("access_token_hint", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_user_id",
            name="oauth_accounts_provider_provider_user_id_key",
        ),
    )
    op.create_index("idx_oauth_user_id", "oauth_accounts", ["user_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint("name = lower(name)", name="tags_name_lower_check"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="tags_user_id_name_key"),
    )
    op.create_index("idx_tags_user_id", "tags", ["user_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("theme", sa.Text(), nullable=False),
        sa.Column("week_starts_on", sa.SmallInteger(), nullable=False),
        sa.Column("default_reminder_time", sa.Time(), nullable=True),
        sa.Column("ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("editor_font", sa.Text(), nullable=False),
        sa.Column("content_language", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "week_starts_on BETWEEN 0 AND 6", name="week_starts_on_check"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "journal_entries",
        sa.Column("day_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::JSONB"),
            nullable=False,
        ),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["day_id"], ["days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_entries_active",
        "journal_entries",
        ["day_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("idx_entries_day_id", "journal_entries", ["day_id"], unique=False)
    op.create_index(
        "idx_entries_favorite",
        "journal_entries",
        ["day_id"],
        unique=False,
        postgresql_where=sa.text("is_favorite = TRUE AND deleted_at IS NULL"),
    )
    op.create_index(
        "idx_entries_search",
        "journal_entries",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_entries_title_trgm",
        "journal_entries",
        [sa.literal_column("title gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "sessions",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("idx_sessions_device_id", "sessions", ["device_id"], unique=False)
    op.create_index("idx_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_table(
        "collection_entries",
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("collection_id", "journal_entry_id"),
    )
    op.create_index(
        "idx_collection_entries_entry",
        "collection_entries",
        ["journal_entry_id"],
        unique=False,
    )
    op.create_table(
        "entry_moods",
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("mood_id", sa.Uuid(), nullable=False),
        sa.Column("intensity", sa.SmallInteger(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "intensity BETWEEN 1 AND 10", name="entry_moods_intensity_check"
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["mood_id"], ["moods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "journal_entry_id",
            "mood_id",
            name="entry_moods_journal_entry_id_mood_id_key",
        ),
    )
    op.create_index(
        "idx_entry_moods_entry", "entry_moods", ["journal_entry_id"], unique=False
    )
    op.create_table(
        "journal_chunks",
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "journal_entry_id",
            "chunk_index",
            name="journal_chunks_journal_entry_id_chunk_index_key",
        ),
    )
    op.create_index(
        "idx_chunks_entry_id", "journal_chunks", ["journal_entry_id"], unique=False
    )
    op.create_index(
        "idx_chunks_hash",
        "journal_chunks",
        ["journal_entry_id", "content_hash"],
        unique=False,
    )
    op.create_table(
        "journal_media",
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("media_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("journal_entry_id", "media_id"),
    )
    op.create_index(
        "idx_journal_media_entry", "journal_media", ["journal_entry_id"], unique=False
    )
    op.create_table(
        "journal_tags",
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("journal_entry_id", "tag_id"),
    )
    op.create_index(
        "idx_journal_tags_entry", "journal_tags", ["journal_entry_id"], unique=False
    )
    op.create_index("idx_journal_tags_tag", "journal_tags", ["tag_id"], unique=False)
    op.create_table(
        "summaries",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("entry", "day", "week", "month", "year", name="summary_scope"),
            nullable=False,
        ),
        sa.Column("kind", sa.Enum("summary", name="summary_kind"), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=True),
        sa.Column("day_id", sa.Uuid(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("highlights", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("challenges", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("themes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "mood_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "(scope = 'entry' AND journal_entry_id IS NOT NULL AND day_id IS NULL AND period_start IS NULL) OR (scope = 'day' AND day_id IS NOT NULL AND journal_entry_id IS NULL AND period_start IS NULL) OR (scope IN ('week', 'month', 'year') AND period_start IS NOT NULL AND period_end IS NOT NULL AND journal_entry_id IS NULL AND day_id IS NULL)",
            name="valid_summary_reference",
        ),
        sa.ForeignKeyConstraint(["day_id"], ["days.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_summaries_day",
        "summaries",
        ["day_id", "kind", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("day_id IS NOT NULL"),
    )
    op.create_index(
        "idx_summaries_entry",
        "summaries",
        ["journal_entry_id", "kind", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("journal_entry_id IS NOT NULL"),
    )
    op.create_index(
        "idx_summaries_period",
        "summaries",
        ["user_id", "scope", "period_start", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("period_start IS NOT NULL"),
    )
    op.create_index(
        "idx_summaries_user",
        "summaries",
        ["user_id", "scope", "kind", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "embeddings",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["journal_chunks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "model", name="embeddings_chunk_id_model_key"),
    )
    op.create_index("idx_embeddings_chunk_id", "embeddings", ["chunk_id"], unique=False)
    op.create_index(
        "idx_embeddings_vector",
        "embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": 100},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_embeddings_vector",
        table_name="embeddings",
        postgresql_using="ivfflat",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": 100},
    )
    op.drop_index("idx_embeddings_chunk_id", table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index("idx_summaries_user", table_name="summaries")
    op.drop_index(
        "idx_summaries_period",
        table_name="summaries",
        postgresql_where=sa.text("period_start IS NOT NULL"),
    )
    op.drop_index(
        "idx_summaries_entry",
        table_name="summaries",
        postgresql_where=sa.text("journal_entry_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_summaries_day",
        table_name="summaries",
        postgresql_where=sa.text("day_id IS NOT NULL"),
    )
    op.drop_table("summaries")
    op.drop_index("idx_journal_tags_tag", table_name="journal_tags")
    op.drop_index("idx_journal_tags_entry", table_name="journal_tags")
    op.drop_table("journal_tags")
    op.drop_index("idx_journal_media_entry", table_name="journal_media")
    op.drop_table("journal_media")
    op.drop_index("idx_chunks_hash", table_name="journal_chunks")
    op.drop_index("idx_chunks_entry_id", table_name="journal_chunks")
    op.drop_table("journal_chunks")
    op.drop_index("idx_entry_moods_entry", table_name="entry_moods")
    op.drop_table("entry_moods")
    op.drop_index("idx_collection_entries_entry", table_name="collection_entries")
    op.drop_table("collection_entries")
    op.drop_index("idx_sessions_expires_at", table_name="sessions")
    op.drop_index("idx_sessions_device_id", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        "idx_entries_title_trgm",
        table_name="journal_entries",
        postgresql_using="gin",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_entries_search", table_name="journal_entries", postgresql_using="gin"
    )
    op.drop_index(
        "idx_entries_favorite",
        table_name="journal_entries",
        postgresql_where=sa.text("is_favorite = TRUE AND deleted_at IS NULL"),
    )
    op.drop_index("idx_entries_day_id", table_name="journal_entries")
    op.drop_index(
        "idx_entries_active",
        table_name="journal_entries",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("journal_entries")
    op.drop_table("user_settings")
    op.drop_index("idx_tags_user_id", table_name="tags")
    op.drop_table("tags")
    op.drop_index("idx_oauth_user_id", table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index("idx_media_user_id", table_name="media")
    op.drop_index(
        "idx_media_pending",
        table_name="media",
        postgresql_where=sa.text("processing_status IN ('pending', 'processing')"),
    )
    op.drop_table("media")
    op.drop_index("idx_devices_user_id", table_name="devices")
    op.drop_table("devices")
    op.drop_index("idx_days_user_date", table_name="days")
    op.drop_table("days")
    op.drop_index("idx_collections_user_id", table_name="collections")
    op.drop_table("collections")
    op.drop_table("users")
    op.drop_table("moods")
    # ### end Alembic commands ###
