"""add version column to journal entries

Revision ID: 9540dac86d69
Revises: 8254be691648
Create Date: 2026-07-03 09:07:54.734314+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9540dac86d69"
down_revision: str | None = "8254be691648"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_entries",
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journal_entries", "version")
    # ### end Alembic commands ###
