"""drop is draft column from journal entries

Revision ID: 8dd287ab96e6
Revises: 9540dac86d69
Create Date: 2026-07-03 09:47:43.014545+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dd287ab96e6"
down_revision: str | None = "9540dac86d69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journal_entries", "is_draft")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_entries",
        sa.Column("is_draft", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
