"""add_user_id_to_embeddings

Revision ID: 5dfd628c3a90
Revises: 66a2a2a2e1b4
Create Date: 2026-07-02 11:35:19.061713+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dfd628c3a90"
down_revision: str | None = "66a2a2a2e1b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("embeddings", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_index("idx_embeddings_user_id", "embeddings", ["user_id"], unique=False)
    op.create_foreign_key(
        None, "embeddings", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "embeddings", type_="foreignkey")
    op.drop_index("idx_embeddings_user_id", table_name="embeddings")
    op.drop_column("embeddings", "user_id")
    # ### end Alembic commands ###
