"""Abstract storage backend interface.

All storage implementations must satisfy this protocol.
Application code should never reference a concrete backend directly —
use ``storage.factory.get_storage()`` instead.
"""

from __future__ import annotations

from abc import ABC, abstractmethod


class StorageBackend(ABC):
    """Abstract base class for object storage backends.

    Implementations:
    - ``storage.local.LocalStorageBackend``
    - ``storage.s3.S3StorageBackend``
    """

    @abstractmethod
    async def upload(self, key: str, data: bytes, content_type: str) -> str:
        """Upload ``data`` and return the storage key.

        Args:
            key: Desired storage path / object key.
            data: Raw bytes to store.
            content_type: MIME type of the file.

        Returns:
            The final storage key (may differ from ``key`` if normalised).
        """

    @abstractmethod
    async def download(self, key: str) -> bytes:
        """Return the raw bytes stored at ``key``.

        Args:
            key: Storage path / object key.

        Raises:
            FileNotFoundError: If no object exists at ``key``.
        """

    @abstractmethod
    async def delete(self, key: str) -> None:
        """Delete the object at ``key``.

        Args:
            key: Storage path / object key to remove.

        Raises:
            FileNotFoundError: If no object exists at ``key``.
        """

    @abstractmethod
    async def get_url(self, key: str, *, expires_in: int = 3600) -> str:
        """Return a URL for accessing the object.

        For local storage this is a signed API endpoint URL.
        For S3 this is a pre-signed GET URL.

        Args:
            key: Storage path / object key.
            expires_in: URL expiry in seconds.

        Returns:
            A URL string.
        """

    @abstractmethod
    async def generate_presigned_put(
        self,
        key: str,
        mime_type: str,
        *,
        expires_in: int = 300,
    ) -> str:
        """Generate a URL the client can use to PUT the object directly.

        For local storage: a signed internal API endpoint.
        For S3/R2: a presigned PUT URL generated by the SDK.

        Args:
            key: Storage path / object key to write to.
            mime_type: Expected Content-Type the client must send.
            expires_in: URL expiry in seconds.

        Returns:
            A URL string the client uses to upload without proxying through the API.
        """

    @abstractmethod
    async def object_exists(self, key: str) -> bool:
        """Return True if an object exists at ``key``, False otherwise.

        Used in the confirm endpoint to verify the client actually uploaded
        the file before transitioning the media record to PROCESSING.

        Args:
            key: Storage path / object key to check.

        Returns:
            True if the object exists, False otherwise.
        """
